name: ai
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.5.0
  - pytorch-lightning
  - torchvision
  - scipy
  - numpy
  - click
  - tqdm
  - pandas
  - nltk
  - pip
  - pip:
      - torchsummary
      - sklearn
      - easydict
      - comet-ml
      - datasets
      - transformers
      - shap
